### ISSUE TITLE
What differents to json.loads ?

### ISSUE THREAD

**Issue by ka1nsha** [khubo/sqliteJson#1]
What differents to json.loads ?

**Comment by khubo** [comment]
@ka1nsha json.loads is for decoding json i suppose.  Probably u mean json.dump, in that case, i would say that json.dumps creates tuples out of sqlite results, but i am trying to convert it into dicts which is similiar to json.

**Comment by ka1nsha** [comment]
But i should use json_loads(sqlqueryvariable).

2017-01-11 11:06 GMT+03:00 Aswin <notifications@github.com>:

**Comment by khubo** [comment]
@ka1nsha sqlite returns tuples. What I was trying to achieve is to convert them into dicts, which is closer to json. Probably you should try running it 💃
